apiVersion: v1
kind: Pod
metadata:
  name: hostpod
  labels:
    app: hostpod
spec:
  containers:
  - name: hostpod
    image: mcr.microsoft.com/containernetworking/azure-npm:v1.4.9
      # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    ports:
    - containerPort: 80
    securityContext:
      privileged: true
  hostNetwork: true
  